---
abstract: 'Perl class for multivariate polynomials'
author:
  - 'Martin Becker <becker-cpan-mp@cozap.com>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.131490'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Math-Polynomial-Multivariate
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  overload: 0
  perl: 5.008
version: 0.004
